# Generated by Django 5.2.8 on 2025-11-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique=True, verbose_name='Слаг'),
            preserve_default=False,
        ),
    ]
